### ISSUE TITLE
[Lack of a basic feature] Implement immediate sync on local changes

### ISSUE THREAD

**Issue by mMuck** [jobisoft/DAV-4-TbSync#90] opened 2019-05-22 22:07 UTC
## Your environment
Current.

## Feature description
Often I add some contact information in TB some minutes before putting my computer to sleep mode. The local changes are detected (TbSync shows an information on the affected accout), but will be synced in the given sync interval (my setting: 60 minutes, but even 5 will not fix this and will produce unnecessarily load on the server connection).

Many apps/adapters/whatever implements a sync (polling) interval but in addition a sync-on-local-changes. This is very easy to implement and would avoid my (and hopefully a general) problem.
The best would be to wait for a given time (option/editable) - default 10 to 20 seconds - after the last change to the local DB and then sync (if its possible) only the affected account and address book.
Is this a thing for the next release? I would be very happy! :smiley: :tada: Thx!!!

**Comment by jobisoft** [comment] 2019-05-22 22:17
Duplicate of
https://github.com/jobisoft/TbSync/issues/258

And yes, it is on the todo list.

**Closed by jobisoft** 2019-05-22 22:17 UTC

**Comment by mMuck** [comment] 2019-05-22 22:27
Oh no. I filed an issue 9 hours "too late". Was not aware that someone could do this first while I had my draft in the browser tab opened for some hours... Perhaps I gave some good ideas to the implementation(?).
But: Perfect. So two users will be happy. :smile:
Thank you for your hard work - even when it's triggered through the TB team decisions.
