### ISSUE TITLE
Compatible with CardBook adding?

### ISSUE THREAD

**Issue by poVoq** [jobisoft/DAV-4-TbSync#69] opened 2019-01-29 09:59 UTC
Have you thought about making this compatible with CardBook?

See:
https://gitlab.com/CardBook/CardBook

**Comment by jobisoft** [comment] 2019-01-29 10:06
I am pushing hard on that one but it takes time, much more than I anticipated.

**Comment by jobisoft** [comment] 2019-02-14 09:40
Duplicate of https://github.com/jobisoft/TbSync/issues/105

**Closed by jobisoft** 2019-02-14 09:40 UTC
