### ISSUE TITLE
Task-only calendar also shows as calendar

### ISSUE THREAD

**Issue by meichthys** [jobisoft/DAV-4-TbSync#294] opened 2021-10-11 20:02 UTC
## Overview
This may be by design, but when syncing task lists with TBSync, the task list also shows up as a calendar. The opposite is also true: If i sync a calendar (no task list desired), the calendar also shows up as a task list.

I think this is probably due to the way CalDav relies on the vCalendar item, but it would sure be nice to completely remove the undesired calendar/task list from the Thunderbird view. It would be nice if we could choose what to sync from the TBSync settings:

![image](https://user-images.githubusercontent.com/10717998/136848535-6b891ade-2c07-4012-b49c-45d72c1fd98e.png)

## Your environment

TbSync version: 3.0.1
Thunderbird version: 91.2.0

## Expected behavior
...
- A Calendar with no vToDo items should be able to be completely hidden from the Task tab in Thunderbird.
- A vCalendar that only contains vToDo items and no events, should be able to be completely hidden from the Calendar tab in Thunderbird.

## Actual behavior
...
The Calendar/TaskList is shown in Thunderbird regardless of user preference

## Steps to reproduce
...

- Create a Task-Only or Calendar-Only vCalendar (I'm doing this via Nextcloud which allows you to create a Task List without a corresponding calendar)
- Sync the TaskList/Calendar to Thunderbird using TBSync
- Try to completely remove the undesired TaskList/Calendar from the Thunderbird tab.

**Comment by jobisoft** [comment] 2022-09-22 10:44
There is currently a bug in Thunderbird 102 (or it is by design, don't know), but even with 
```
newCalendar.setProperty("capabilities.tasks.supported", false);
```
the calendar is still shown in the task tab (and vica versa). But it is not possible to actually use them, if they are marked as unsupported.

I did manage to pick up the information from the server. Fruux populates the `supported-calendar-component-set` property and I can use that to identify pure VTODO calendars:

![image](https://user-images.githubusercontent.com/5830621/191725791-3e29d984-f3c7-4edc-ae5f-acbb326df752.png)

So now we have the todo icon in the list and the supported property is set.

Can you give it a try? (TB102!) Does it work with your server? I will not manually check the elements in the calendar, so if your server is not sending the `supported-calendar-component-set` property, I see no way to fix it for you.

TbSync 3.3: [TbSync-beta.zip](https://github.com/jobisoft/DAV-4-TbSync/files/9624872/TbSync-beta.zip)
Dav 2.3: [DAV-4-TbSync.zip](https://github.com/jobisoft/DAV-4-TbSync/files/9624878/DAV-4-TbSync.zip)

**Comment by meichthys** [comment] 2022-09-22 12:18
Wow, great to see you're working on this! Do you know if it would work on TB 105?
For some reason I thought TBSync was mostly merged into Thunderbird and that it wasn't really needed anymore.
Is there some place in the wiki or docs that clarify the differences between TBSync and the built in CalDav setup wizard?

**Comment by jobisoft** [comment] 2022-09-22 13:31
I concentrate on ESR releases, which was already difficult. I do not have the time to keep up with beta.

TbSync is now using the standard CalDAV and CardDAV sync capabilities of Thunderbird (I no longer use my own sync code), but the easy setup and management through the TbSync interface is still requested by some users, so I updated that for 102.

There should be no difference between manually setting up calendars and address books, or using TbSync. My auto discover is a bit better and works with iCloud.

**Comment by meichthys** [comment] 2022-09-22 14:15
Ok, Thanks!
Does TBSync handle the importing of calendars differently? In other words, Could it fix this issue while the built in capabilities in Thunderbird still have the issue?

**Comment by jobisoft** [comment] 2022-09-22 14:39
I am now setting the capability flag according to the received information from the `supported-calendar-component-set` property. I assume that Thunderbird was already correctly setting the capability flag, when you set up a calendar through the built-in setup wizard (but I am not sure).

Thunderbird honours this capability flag when creating new events/task but does not honour it when listing calendars in the task or calendar tab. I am not changing that, but will ask a core developer if this is a bug which should be fixed in core.

**Closed** 2022-09-22 14:43 UTC
Labels: enhancement

**Comment by meichthys** [comment] 2022-09-22 15:11
Just for reference, I think this issue is related: https://bugzilla.mozilla.org/show_bug.cgi?id=1739705
