### ISSUE TITLE
Cardav Error on contact group 

### ISSUE THREAD

**Issue by brocasm** [jobisoft/DAV-4-TbSync#251] opened 2021-01-14 14:57 UTC
## Your environment

TbSync version: 2.19
DAV-4-TbSync version: 1.21
Thunderbird version: 78

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...
Send a email to a group of contact

## Actual behavior
...
When try to add the group  in To: 
 It will be found but with no text and no adress.
It's not possible to send any mail

## Steps to reproduce
...
In adress book, create a group with any contact inside all with email adress.
Write a mail, select the goup name in the to element.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
![1](https://user-images.githubusercontent.com/56800814/104607393-118aa180-5681-11eb-9e9c-2c49deafb8a2.PNG)
![2](https://user-images.githubusercontent.com/56800814/104607395-12bbce80-5681-11eb-9e57-26c5f3d9c50e.PNG)

**Comment by jobisoft** [comment] 2021-01-16 09:57
Can you update to the lastest version?
https://addons.thunderbird.net/de/thunderbird/addon/dav-4-tbsync/versions/

Any change?

**Comment by codedoneright-eu** [comment] 2021-06-22 16:08
Looks like the issue is still present. 

TbSync version: 2.22
DAV-4-TbSync version: 1.24
Thunderbird version: 78.11

![image](https://user-images.githubusercontent.com/61863034/122959714-672b4e80-d383-11eb-8d6f-1444c4a6b988.png)

**Comment by jobisoft** [comment] 2022-09-21 15:17
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird feature request.

**Closed by jobisoft** 2022-09-21 15:17 UTC
